version = 0.1

[default.deploy.parameters]
stack_name = "backend-template"
resolve_s3 = true
s3_prefix = "backend-template"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "GoogleWebClientId=361957661663-0puuujqcq0bpr83vo32ue7hbod8egl1o.apps.googleusercontent.com"

[default.global.parameters]
region = "ap-northeast-2"
